* financial performance measures
Solvency,Method of Computation,Use,

Working Capital,Current Assets - Current Liabilites,To indicate the ability to meet curently maturing obligations,
,
Current Ratio,Current Assets/Current Liabilites,To indicate the ability to meet currently maturing obligations,
,
Acid -Test Ratio,Quick Assets/Current Liabilites,To indicate instant debt-paying ability,
Inventory Turnover,Cost of Goods Sold/Average Inventory,To assess the efficiency in the management of inventory,
,
Number of Days' Sales in Inventory,Inventory (EOY)/Average Daily Cost of Goods Sold,To assess the efficency in the management of inventory,
,
"Ratio of Fixed Assets to
Long-term Liabilities",Net Fixed Assets/Long-term Liabilities,To indicate the margin of safety to long-term creditors,
* inventory turnover
** calculation
cost of goods sold / average inventory
where average inventory is (inventory_beg + inventory_end) / 2
** TODO usage
** TODO reasons used
* budgeting
** [#B] most controllable expense
payroll
* Medication Therapy Management
** group project :ignore:
- if we say we made an ad, we have to create and show and example of the ad
** billing
*** TODO [#A] CPT codes
- 99605: initial meeting with patient
- 99606:
- 99607:
* marketing
** being remarkable---how to make your customers happy
consistently…
- solve their problems
- make them feel good
** role of marketing :l:
*** production
*** product
*** selling
*** market/customer
** marketing mix variables---4 Ps :l:
*** product
- pharmacy as a tangible product vs. as a service
- bottle of pills vs. pharmaceutical care service
- brand vs. generic
*** place
*** price
**** total price, breakdown
total price = cost of goods sold + cost to dispense + profit
**** considerations
- demand, inelastic vs. elastic
- product vs. service
**** strategies
- loss-leader pricing
- psychological pricing
- promotional pricing
- bundling and couponing
*** promotion

